import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p className={styles.paragraph}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae aut unde commodi omnis quod officia dicta quidem reprehenderit deserunt. Culpa atque, mollitia, doloremque perferendis voluptate tempora voluptates sunt quod autem error, enim dolore consequuntur commodi laboriosam excepturi? Minus consectetur temporibus tempore vero beatae earum dignissimos quasi et necessitatibus neque sit, dolore magnam, est quis molestiae quisquam voluptate saepe maxime harum minima vel, consequatur at! Exercitationem alias nesciunt soluta autem! Dolorum voluptatem laboriosam labore voluptate, reprehenderit facere nisi quae veritatis maiores id at sit, architecto ducimus libero nobis. Rerum praesentium dolorem autem magnam quasi exercitationem, fugiat quidem quos tempore quam nobis!</p>
    </div>
  )
}

export default Home
